<?php
/**
 * Created by PhpStorm.
 * User: lenovo
 * Date: 12.09.2017
 * Time: 15:43
 *
 * @author Pavel Shulaev (https://rover-it.me)
 */

namespace Rover\Fadmin\Layout\Admin\Input;

use Rover\Fadmin\Layout\Admin\Input;

/**
 * Class Radio
 *
 * @package Rover\Fadmin\Layout\Admin\Input
 * @author  Pavel Shulaev (https://rover-it.me)
 */
class Radio extends Input
{
    /**
     * @return mixed|void
     * @throws \Bitrix\Main\ArgumentNullException
     * @throws \Bitrix\Main\ArgumentOutOfRangeException
     * @author Pavel Shulaev (https://rover-it.me)
     */
    public function showInput()
    {
        if (!$this->input instanceof \Rover\Fadmin\Inputs\Radio)
            return;

        $value = $this->input->getValue();

        foreach ($this->input->getOptions() as $optionValue => $optionName):

            ?><label><input <?=$this->getCommonAttributes()?>
                <?=$value == $optionValue ? ' checked="checked" ' : ''
                ?>> <?=$optionName?></label><br><?php

        endforeach;
    }

    public function getValue()
    {
        return parent::getValue(); // TODO: Change the autogenerated stub
    }
}